// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuHluvG62AvM26KycVYtOXh9M7y0Z9OA',
    appId: '1:134490843472:web:233d76977889e4899ea455',
    messagingSenderId: '134490843472',
    projectId: 'skillsprint-10e8c',
    authDomain: 'skillsprint-10e8c.firebaseapp.com',
    storageBucket: 'skillsprint-10e8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYX6s-qS43ej1gh_i1_vaUhIloT7zTwnA',
    appId: '1:134490843472:android:98bf7cd992a72b669ea455',
    messagingSenderId: '134490843472',
    projectId: 'skillsprint-10e8c',
    storageBucket: 'skillsprint-10e8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByYm_Gp8rBjNMp25FtVp9Hy0baP180bQQ',
    appId: '1:134490843472:ios:0b2cc9ee873a6e519ea455',
    messagingSenderId: '134490843472',
    projectId: 'skillsprint-10e8c',
    storageBucket: 'skillsprint-10e8c.firebasestorage.app',
    iosBundleId: 'com.example.skillsprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByYm_Gp8rBjNMp25FtVp9Hy0baP180bQQ',
    appId: '1:134490843472:ios:0b2cc9ee873a6e519ea455',
    messagingSenderId: '134490843472',
    projectId: 'skillsprint-10e8c',
    storageBucket: 'skillsprint-10e8c.firebasestorage.app',
    iosBundleId: 'com.example.skillsprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUuHluvG62AvM26KycVYtOXh9M7y0Z9OA',
    appId: '1:134490843472:web:9dc4e48c7a59c08f9ea455',
    messagingSenderId: '134490843472',
    projectId: 'skillsprint-10e8c',
    authDomain: 'skillsprint-10e8c.firebaseapp.com',
    storageBucket: 'skillsprint-10e8c.firebasestorage.app',
  );
}
